apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: cert-wfslab
  namespace: ingress-nginx  # O mesmo do NGINX
spec:
  domains:
    - homologacao.wfslab.com.br
    - producao.wfslab.com.br