name: Deploy no Kubernetes

on:
    workflow_call:
      inputs:
        environment-name:
          type: string
          required: true
        inputs.environment-url:
          type: string
          required: true

jobs:
    deploy:
        name: "Deploy"
        runs-on: ubuntu-Latest
        environment:
          name: ${{ inputs.environment-name}}
          url: ${{ inputs.environment-url}}
        steps:
            - name: Obtendo o código
              uses: actions/checkout@v4
            
            # - name: Configurando o cluster no GKE
            #   uses: azure/k8s-set-context@v4
            #   with:
            #     method: kubeconfig
            #     kubeconfig: ${{ secrets.K8S_CONFIG }}

            - name: Auth no Google Cloud
              uses: google-github-actions/auth@v2
              with:
                workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_ID }}
                service_account: ${{ vars.SERVICE_ACCOUNT_ID }}

            - name: Configurar acesso ao GKE
              uses: google-github-actions/get-gke-credentials@v2
              with:
                cluster_name: ${{ vars.CLUSTER_NAME }}
                location: ${{ vars.REGION }}
                project_id: ${{ vars.PROJECT_ID }}

            - name: Update Deployment
              run: "sed -i 's/host: homologacao.wfslab.com.br/host: ${{ vars.BASE_URL }}/g' k8s/deployment.yaml"
            
            - name: Deploy no Kubernetes
              uses: Azure/k8s-deploy@v5
              with:
                namespace: ${{ secrets.K8S_NAMESPACE }}
                manifests: |
                    k8s/deployment.yaml
                images: |
                    ${{ vars.REGION }}-docker.pkg.dev/${{ vars.PROJECT_ID }}/${{ vars.REPOSITORY }}/${{ vars.IMAGE_NAME }}:v${{ github.run_number }}
